### ISSUE TITLE
Username is empty

### ISSUE THREAD

**Issue by 2naive** [DenisIndenbom/AntiToxicBot#1]
https://github.com/DenisIndenbom/AntiToxicBot/blob/68f46ab0e77fa8fdd07f572674b75ce08395eb87/main.py#L243

If username is not set:
`None|rating -0.25|toxic 1|positive 0|`
https://core.telegram.org/constructor/user
-- concatenation of first_name and last_name should be used.

**Comment by DenisIndenbom** [comment]
ok, thanks

**Comment by DenisIndenbom** [comment]
I fixed the bug. Can I close issue?
